In [10]:
import numpy as np
import pandas as pd

matrix1 = np.array([[1, 1], [2, 2], [3, 3]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

print('3 x 2 matrix is below : \n', matrix1)
print('\n 2 x 3 matrix is below: \n', matrix2)

3 x 2 matrix is below : 
 [[1 1]
 [2 2]
 [3 3]]

 2 x 3 matrix is below: 
 [[1 2 3]
 [4 5 6]]


In [11]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.66215119 0.3298971  0.78208529 0.35758799]
 [0.79301901 0.41122753 0.3911968  0.42214953]
 [0.42758778 0.3704204  0.98750293 0.15698083]]


In [12]:
# matrix multiplication
m3 = np.dot(matrix1, matrix2)
print(m3)

[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


In [13]:
# elemet wise matrix multiplication
result = [[0 for x in range(len(matrix1))] for y in range(len(matrix2[0]))]

for i in range(len(matrix1)): 
  for j in range(len(matrix2[0])): 
    for k in range(len(matrix2)): 
      result[i][j] += matrix1[i][k] * matrix2[k][j]
 
print('Element-wise multiplication : \n', result)

Element-wise multiplication : 
 [[5, 7, 9], [10, 14, 18], [15, 21, 27]]


In [14]:
mean = np.mean(matrix1)
print(mean)

2.0


In [9]:
data = pd.read_csv('mtcars.csv')
print (data)

                  model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.

In [15]:
#author - CE111 
del data['model']

meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())



        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
