In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch



## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges


In [2]:

# Imports
import torch.nn as nn

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')



In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("Inputs : \n",inputs)
print("Targets : \n",targets)



Inputs : 
 tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
Targets : 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.



In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [5]:

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


In [6]:

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break



tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [103., 119.],
        [ 56.,  70.],
        [ 22.,  37.],
        [103., 119.]])


### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.


In [7]:

# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[ 0.5353,  0.1843, -0.0359],
        [-0.0210,  0.1704, -0.3737]], requires_grad=True)
Parameter containing:
tensor([-0.2980, -0.3614], requires_grad=True)


In [8]:

# Parameters
list(model.parameters())


[Parameter containing:
 tensor([[ 0.5353,  0.1843, -0.0359],
         [-0.0210,  0.1704, -0.3737]], requires_grad=True),
 Parameter containing:
 tensor([-0.2980, -0.3614], requires_grad=True)]

In [9]:

# Generate predictions
preds = model(inputs)
preds


tensor([[ 49.5782,  -6.5513],
        [ 62.3281, -11.2005],
        [ 68.8793,  -1.0379],
        [ 60.8944,  -9.0059],
        [ 51.8104, -11.6184],
        [ 49.5782,  -6.5513],
        [ 62.3281, -11.2005],
        [ 68.8793,  -1.0379],
        [ 60.8944,  -9.0059],
        [ 51.8104, -11.6184],
        [ 49.5782,  -6.5513],
        [ 62.3281, -11.2005],
        [ 68.8793,  -1.0379],
        [ 60.8944,  -9.0059],
        [ 51.8104, -11.6184]], grad_fn=<AddmmBackward>)

In [10]:

# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)



### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.


In [11]:

# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

#loss = loss_fn(? , ?)
#print(loss)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.


In [12]:

# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)



### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.


In [13]:

# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
   print('Training loss: ', loss_fn(model(inputs), targets))


In [14]:

# Train the model for 100 epochs
fit(100 , model , loss_fn, opt)


Training loss:  tensor(50.7229, grad_fn=<MseLossBackward>)


In [15]:

# Generate predictions
preds = model(inputs)
preds


tensor([[ 58.9800,  71.8297],
        [ 80.2347,  96.3540],
        [120.9709, 141.1809],
        [ 31.0367,  44.9872],
        [ 92.5688, 106.8447],
        [ 58.9800,  71.8297],
        [ 80.2347,  96.3540],
        [120.9709, 141.1809],
        [ 31.0367,  44.9872],
        [ 92.5688, 106.8447],
        [ 58.9800,  71.8297],
        [ 80.2347,  96.3540],
        [120.9709, 141.1809],
        [ 31.0367,  44.9872],
        [ 92.5688, 106.8447]], grad_fn=<AddmmBackward>)

In [16]:

# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])