#Task 1: Try the algo on Dataset3 - OneHotEncoding of features:and Train test Division 85%-15%

In [7]:
#ce111
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [29]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [30]:
# Loading dataset
dataset = pd.read_csv("/content/drive/My Drive/Colab/Dataset3.csv")

In [36]:
label_encoder = preprocessing.LabelEncoder()
yrows = None
for data_heading in dataset:
  # print(data_heading)
  if (data_heading != 'Class') :
    print(f'\n\nHeading  :-  {data_heading}')
    dummy = pd.get_dummies(dataset[data_heading])
    dataset = dataset.drop([data_heading], axis = 1)
    dataset = pd.concat([dataset, dummy], axis = 1)
  else:
    yrows = label_encoder.fit_transform(dataset[data_heading])
    dataset = dataset.drop([data_heading], axis = 1)



Heading  :-  F


Heading  :-  T


Heading  :-  O


Heading  :-  R


Heading  :-  S


Heading  :-  Temp


Heading  :-  Humidity


In [43]:
print(dataset)
print(yrows)

    0  1  0  1  0  1  0  1  0  1  0  1  2  0  1  2
0   0  1  1  0  1  0  0  1  1  0  0  1  0  0  1  0
1   1  0  0  1  1  0  0  1  1  0  0  1  0  0  0  1
2   0  1  1  0  0  1  1  0  1  0  0  1  0  0  1  0
3   0  1  1  0  1  0  0  1  1  0  0  0  1  0  1  0
4   0  1  1  0  1  0  1  0  0  1  1  0  0  0  1  0
5   1  0  0  1  0  1  1  0  1  0  1  0  0  1  0  0
6   1  0  0  1  0  1  1  0  1  0  1  0  0  0  1  0
7   0  1  1  0  1  0  0  1  1  0  0  0  1  0  1  0
8   0  1  1  0  0  1  1  0  1  0  1  0  0  1  0  0
9   0  1  1  0  1  0  1  0  0  1  0  0  1  0  0  1
10  1  0  0  1  1  0  0  1  1  0  1  0  0  0  0  1
11  1  0  0  1  0  1  1  0  1  0  0  0  1  1  0  0
12  0  1  1  0  0  1  1  0  1  0  0  1  0  0  1  0
13  1  0  0  1  1  0  1  0  0  1  0  0  1  0  1  0
[0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [44]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(dataset, yrows, test_size = 0.15, random_state = 111)

In [45]:
model = MultinomialNB()
model.fit(xtrain, ytrain)

y_predicted = model.predict(xtest)
print(xtest)
print('\n', y_predicted)

    0  1  0  1  0  1  0  1  0  1  0  1  2  0  1  2
10  1  0  0  1  1  0  0  1  1  0  1  0  0  0  0  1
5   1  0  0  1  0  1  1  0  1  0  1  0  0  1  0  0
7   0  1  1  0  1  0  0  1  1  0  0  0  1  0  1  0

 [0 1 1]


In [46]:
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print(f'Accuracy is  :-  {metrics.accuracy_score(ytest, y_predicted)}')

#precision and recall
precision = precision_score(ytest, y_predicted)
recall = recall_score(ytest, y_predicted)
print(f'Precision  :-  {precision}')
print(f'Recall  :-  {recall}')

Accuracy is  :-  0.3333333333333333
Precision  :-  0.0
Recall  :-  0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 66%-34%

In [48]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine

wine_data = load_wine()
print('Features : \n', wine_data.feature_names)
print('\nLabels : \n', wine_data.target_names)
wine_data.data.shape

Features : 
 ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Labels : 
 ['class_0' 'class_1' 'class_2']


(178, 13)

In [49]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(wine_data.data, wine_data.target, test_size = 0.34, random_state = 111)

In [50]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)   #train the model using training sets
target_prediction = gnb.predict(data_test)  #predict the response of test dataset

In [51]:
from sklearn import metrics

print('Accuracy of model  :  ', metrics.accuracy_score(target_test, target_prediction))

Accuracy of model  :   0.9672131147540983


In [52]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_prediction)

array([[20,  1,  0],
       [ 0, 24,  1],
       [ 0,  0, 15]])

In [53]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_prediction, average = None)
recall = recall_score(target_test, target_prediction, average = None)

print('Precision  :  {}'.format(precision))
print('\n\nRecall  :  {}'.format(recall))

Precision  :  [1.     0.96   0.9375]


Recall  :  [0.95238095 0.96       1.        ]
